// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apmyxyrrauthjmifpbbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwbXl4eXJyYXV0aGptaWZwYmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTUyOTMsImV4cCI6MjA2OTgzMTI5M30.kr293_LfeeamiuA6nOEjQYnb2hWpgpNRKK_OjXO1STY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});